const questions = [
    "Average number of minutes you read each day",
    "Average number of minutes you watch TV each day",
    "Average number of minutes you spend talking to people in person daily",
    "Average number of minutes you spend brushing your teeth each day",
    "Average number of minutes you spend getting dressed each day",
    "Average number of minutes you spend doing homework or studying each day",
    "Average number of minutes you spend playing outside each day",
    "Average number of minutes you spend watching YouTube or online videos each day",
    "Average number of minutes you spend listening to music each day",
    "Average number of minutes you spend cooking or preparing food each day",
    "Average number of minutes you spend cleaning or tidying up each day",
    "Average number of minutes you spend exercising or moving your body each day",
    "Average number of minutes you spend commuting or traveling each day",
    "Average number of minutes you spend playing video games each day",
    "Average number of minutes you spend on social media each day",
    "Average number of minutes you spend relaxing or doing nothing each day",
    "Average number of minutes you spend drawing or crafting each week",
    "Average number of minutes you spend playing a musical instrument each week",
    "Average number of minutes you spend dancing each week",
    "Average number of minutes you spend writing stories or journaling each week",
    "Average number of minutes you spend watching movies each week",
    "Average number of minutes you spend playing board games or card games each week",
    "Average number of minutes you spend doing puzzles each week",
    "Average number of minutes you spend doing something creative each week",
    "Average number of minutes you spend stretching or doing yoga each week",
    "Average number of minutes you spend meditating or praying each week",
    "Average number of minutes you spend getting ready for bed each night",
    "Average number of minutes you spend drinking water each day",
    "Average number of minutes you spend eating meals each day",
    "Average number of minutes you spend outside in nature each week",
    "Average number of minutes you spend doing chores each week",
    "How many people do you talk to in person each day",
    "How many messages do you send each day",
    "How many people do you see outside your household each week",
    "How many hugs do you give or receive each week",
    "How many times do you laugh each day",
    "How many times do you say “thank you” each day",
    "How many times do you help someone each week",
];